### ISSUE TITLE
"Beta" website TODO list

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#209]
- [ ] Make "Top Players" and "Latest Users" modules like on Enjin
- [ ] Fix "Recent Voters" module on vote page
- [x] Updated announcement on home page
- [x] Redesign applications page
- [x] Update ModCP Meeting Notes --> Most Recent Meeting Notes?
- [ ] Fix "Forgot my password" system
- [x] Redesign the look of the Top Voters section

**Comment by Pugabyte** [comment]
Rewriting to java incoming, closing
