### ISSUE TITLE
[1.13] Todo list

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#259]
- [x] Switch from VNP to PremiumVanish (PV)
- [x] Fix WGEF
- [x] Find/make a Heavyspleef alternative
- [ ] Disable phantom spawning for players in creative ~~, and in vanish~~ (fixed by PV)
- [x] ~~Fix `||` in lore~~
- [x] Fix `converted to seconds` throwing errors (when being parsed as a number?)
- [x] ~~Fix pasting schematics in skript~~
- [x] ~~ImageToMap images~~
- [x] Finish spawn
- [x] ~~Fix bridge json stuff~~
- [ ] Remove PStones? - Get opinions from staff team
